FROM opensuse/leap:15.2
RUN groupadd dummy ; useradd -d /dummy/ -m -g dummy dummy ; \
#echo 'dummy ALL=NOPASSWD: ALL' >> /etc/sudoers ; \
zypper --non-interactive --ignore-unknown --no-cd install --auto-agree-with-licenses --allow-unsigned-rpm \
java-11-openjdk-headless sudo curl ; \
zypper --non-interactive clean -a ; zypper --non-interactive purge-kernels
