FROM aashipov/roster:base
USER root
RUN zypper --non-interactive --ignore-unknown --no-cd install --auto-agree-with-licenses --allow-unsigned-rpm \
maven ; \
zypper --non-interactive clean -a ; zypper --non-interactive purge-kernels; \
mkdir -p /dummy/build/ ; chown -R dummy:dummy /dummy/build/
